# Generated by Django 4.2.1 on 2023-05-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='github',
            field=models.URLField(default=1, max_length=100, verbose_name='GitHub'),
            preserve_default=False,
        ),
    ]
